---
title: "table_s2"
author: "Jianyu"
date: "3/5/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lmec)
library(lme4)
source("z_create_matrix.R")
source("fixRNAscientific.R")
set.seed(42)
```

```{r}
dF <- read.csv(file = "../working_files/nonpaired_pcr_sx_rpr.csv")
# geometric mean function
gm_mean <- function(x, na.rm=TRUE) {
  y <- exp(sum(log(x[x > 0]), na.rm=na.rm) / length(x))
  return(y)
}
```
# Counts of tested cases, samples (at LOD, LOQ), culture status
```{r}
tested_case_samp_df <- dF %>% distinct(subject_id, sample_date, sample_type) %>% group_by(sample_type) %>%
  summarize(Cases = length(unique(subject_id)),`qPCR Samples` = n())
tested_case_samp_df

# Count samples >LOD, LOQ
pos_samp_df <- dF %>% distinct(subject_id, sample_date, sample_type,.keep_all = T) %>% group_by(sample_type) %>%
  summarize(n_lod1 = sum(any_rep_lod1),
            n_lod2 = sum(all_rep_lod2),
            n_loq = sum(loq))
pos_samp_df

n_sid_lod1_df <- dF %>% filter(any_rep_lod1)
n_sid_lod1_df <- n_sid_lod1_df%>% mutate(ur=formatC(max(sample_quant),format = "e", digits = 1)) %>% distinct(sample_id,.keep_all = T) %>% group_by(sample_type) %>%
  summarize(n_sid_lod1=length(unique(subject_id)),
            upperRange=formatC(max(ur),format = "e", digits = 1)) #this is upper bound of any_rep_lod samples
n_sid_lod1_df

n_sid_lod2_df <- dF %>% filter(all_rep_lod2)
n_sid_lod2_df <- n_sid_lod2_df %>% distinct(sample_id,.keep_all = T) %>% group_by(sample_type) %>%
  summarize(n_sid_lod2=length(unique(subject_id)))
n_sid_lod2_df

n_sid_loq_df <- dF %>%filter(loq)
n_sid_loq_df <- n_sid_loq_df %>% distinct(sample_id,.keep_all = T) %>% group_by(sample_type) %>%
  summarize(n_sid_loq=length(unique(subject_id)))
n_sid_loq_df

culture_df <- dF %>% filter(culture_status!="not cultured") %>%
                distinct(sample_id, sample_type,.keep_all = T) %>% group_by(sample_type) %>%
                summarize(n_samp_culture = n(),
                          n_sid_culture = length(unique(subject_id)),
                          n_samp_culture_pos = sum(culture_status=="TRUE"))
culture_df <- culture_df %>% mutate(n_samp_culture_pos_per =round((n_samp_culture_pos/n_samp_culture)*100,0))
culture_df

n_sid_culture_pos <- dF %>% filter(culture_status=="TRUE") %>% distinct(sample_id,.keep_all = T) %>% group_by(sample_type) %>%
  summarize(n_sid_culture_pos = length(unique(subject_id)))
n_sid_culture_pos
```

#  Geometric mean, Geometric SD for positive cases
```{r}
gm_gsd_df <- dF %>% filter(nd_lod_loq != 0)
gm_gsd_df <- gm_gsd_df %>% group_by(sample_id) %>% mutate(hq=(sample_quant==max(sample_quant)),
                                                          av_per_sample_id=mean(sample_quant,na.rm = T))
# hq identifies the row(s) with highest sample_quant in every group of replicate
# av_per_sample_id estimates the average sample_quant for every group of 2-replicates excluding non-detects

gm_gsd_df <- gm_gsd_df %>% distinct(sample_id,.keep_all = T) %>% group_by(sample_type)
gm_gsd_df <- gm_gsd_df%>% summarize(
  arith_ave=mean(av_per_sample_id),
  Max_ave_per_sample=paste(formatC(max(av_per_sample_id), format = "e", digits = 1)), #this range will give range for any LOD
  n_samp_included_in_gm_est=n(),
  GM_positive_samples_only = formatC(gm_mean(av_per_sample_id),format = "e", digits = 1))

gm_gsd_df
```

```{r}
partial_summary <- tested_case_samp_df %>%
  left_join(pos_samp_df, by="sample_type") %>%
  left_join(n_sid_lod1_df, by="sample_type") %>%
  left_join(n_sid_lod2_df, by="sample_type") %>%
  left_join(n_sid_loq_df, by="sample_type") %>%
  left_join(culture_df, by="sample_type") %>%
  left_join(n_sid_culture_pos, by="sample_type") %>%
  left_join(gm_gsd_df, by="sample_type")
partial_summary
```

# Compute sample percentages and case percentages
```{r}  
full_summary <- partial_summary %>% mutate(
  n_lod1_perc=round((n_lod1/`qPCR Samples`)*100,0),
  n_lod2_perc=round((n_lod2/`qPCR Samples`)*100,0),
  n_loq_perc=round((n_loq/`qPCR Samples`)*100,0),
  n_sid_lod1_perc=round((n_sid_lod1/Cases)*100,0),
  n_sid_lod2_perc=round((n_sid_lod2/Cases)*100,0),
  n_sid_loq_perc=round((n_sid_loq/Cases)*100,0),
  n_sid_culture_pos_per=round((n_sid_culture_pos/n_sid_culture)*100,0))
full_summary
```

```{r}
summary_wo_gm <- full_summary %>% mutate(
  `Participants LOD`=paste0(n_sid_lod1,"/",Cases," (",n_sid_lod1_perc,")"),
  `Participants LOQ`=paste0(n_sid_loq,"/",Cases," (",n_sid_loq_perc,")"),
  `Participants Culture pos n/N` = paste0(n_sid_culture_pos,"/",n_sid_culture," (",n_sid_culture_pos_per,")"),
  `Samples LOD`= paste0(n_lod1,"/",`qPCR Samples`," (",n_lod1_perc,")"),
  `Samples LOQ`=paste0(n_loq,"/",`qPCR Samples`," (",n_loq_perc,")"),
  `Culture n/N (% Positive)`=paste0(n_samp_culture_pos,"/",n_samp_culture," (",n_samp_culture_pos_per,")"))

summary_wo_gm <- summary_wo_gm %>% select(sample_type,Cases,`qPCR Samples`,upperRange,Max_ave_per_sample,GM_positive_samples_only,`Participants LOD`,`Participants LOQ`,`Participants Culture pos n/N`,`Samples LOD`,`Samples LOQ`,`Culture n/N (% Positive)`)
summary_wo_gm
```

## LMEC
Cut individual sample type datasets
```{r}
pcr_dat_clean <- dF %>% mutate(ln_final_copies=log(mdfy_sample_quant))
pcrdatclean_sampletypes <- pcr_dat_clean$sample_type %>% unique()

sarslist <- pcrdatclean_sampletypes %>% lapply(function(x) {pcr_dat_clean %>% filter(sample_type==x)})
names(sarslist) <- pcrdatclean_sampletypes

sarslist_sid_samp <- sarslist %>% lapply(function(x) {x %>% summarise(sid = n_distinct(subject_id),samples = n_distinct(subject_id,sample_date))})
sarslist_sid_samp %>% unlist()

sarslist_zmatrix <- sarslist %>% lapply(z_create_matrix)
```
# Construct models and extract GM and GSD
```{r}
ef_est_reml_df_list <- list()

pcrdatclean_sampletypes1 <- pcrdatclean_sampletypes %>% subset(!(grepl("IcePac|Cone",.)))

for (q in pcrdatclean_sampletypes1) {
  
  # MODEL FOR: 
  print(q)
  
  sarsdataset <- sarslist[[q]]
  Z_current <- z_create_matrix(sarsdataset)
  vars <- c("intercept", "subject_id") # naming for table creation later on.
  X <- matrix(rep(1, length(sarsdataset$ln_final_copies)), ncol=1) #for intercept only
  cluster <- as.numeric(as.factor(sarsdataset$subject_id))
  
  #### MODEL: Running the LMEC procedures: using REML ####

  fit_reml <- lmec(yL = sarsdataset$ln_final_copies,
                  cens = sarsdataset$cens,
                  X = X, 
                  Z = Z_current,
                  cluster=cluster,
                  method='ML',
                  maxstep=200)
  summary(fit_reml)
  print(fit_reml)
  
  #### Taking model parameter estimates and using to generate GM (GSD) and confidence interval ####
  betas <- length(fit_reml$beta) 
  n <- length(sarsdataset$subject_id)
  ef_est <- c()
  low_ci <- c()
  up_ci <- c()
  ef_est_reml <- c()
  
  for (i in 1:betas) {
                  beta <- fit_reml$beta[i]
                  sigma <- sqrt(fit_reml$varFix[i])
                  low_ci_fold_inc <- signif(exp(beta - 1.96*(sigma)), 2)
                  up_ci_fold_inc <- signif(exp(beta + 1.96*(sigma)), 2)
                  fold_inc <- signif(exp(beta), 2)
                  var <- vars[i]
                  fold_inc_var <- cbind(var, fold_inc, low_ci_fold_inc, up_ci_fold_inc)
                  ef_est_reml <- rbind(ef_est_reml, fold_inc_var)
  }
  
  ef_est_reml_df <- as.data.frame(ef_est_reml) %>%
                  mutate(fold_inc = formatC(as.numeric(as.character(fold_inc)), format = "e", digits = 1),
                         low_ci_fold_inc = formatC(as.numeric(as.character(low_ci_fold_inc)), format = "e", digits = 1),
                         up_ci_fold_inc = formatC(as.numeric(as.character(up_ci_fold_inc)), format = "e", digits = 1)) %>% 
                  unite("95% CI", low_ci_fold_inc, up_ci_fold_inc, sep = ", ") %>%
                  mutate(`95% CI` = paste0("(", `95% CI`, ")")) %>%
                  unite("effect_ci",  fold_inc, `95% CI`, sep = " ") %>%
                  mutate(gsd = signif(exp(fit_reml$sigma), digits = 2))
  
  print(ef_est_reml_df)
  ef_est_reml_df_list[[q]] <- ef_est_reml_df

}
```

## Final GM table
```{r}
gm_table1 <- bind_rows(ef_est_reml_df_list)
gm_table1$`Sample Type` <- names(ef_est_reml_df_list)
gm_table1 <- gm_table1 %>% arrange(`Sample Type`)
gm_table1 <- gm_table1 %>% rename(`GM (95% CI)` = effect_ci,`GSD` = gsd) %>% select(`Sample Type`,`GM (95% CI)`,`GSD`)
```


Bind summary_wo_gm with gm_table 
```{r}
table_df <- merge(summary_wo_gm,gm_table1,by.x = "sample_type",by.y = "Sample Type")
table_df <- table_df %>% filter(sample_type %in% c("Midturbinate Swab","Saliva","Phone Swab","G-II Coarse Aerosol","G-II Fine Aerosol"))

# rename and reorder cols
Table2 <- table_df %>% rename(`Sample Type`=sample_type,`Samples`="qPCR Samples",`Maximum RNA copies`="Max_ave_per_sample")
#Table2 <- Table2 %>% select(`Sample Type`,Cases,`Participants LOD`,`Participants LOQ`,`Participants Culture pos n/N`,Samples,`Samples LOD`,`Samples LOQ`,`Culture n/N (% Positive)`,`GM (95% CI)`,`Maximum RNA copies`)
Table2 <- Table2 %>% select(`Sample Type`,`Participants LOD`,`Participants Culture pos n/N`,`Samples LOD`,`Culture n/N (% Positive)`,`GM (95% CI)`,`Maximum RNA copies`)

# rename and reorder rows
Table2$`Sample Type`[Table2$`Sample Type`=="Phone Swab"] <- "Fomite"
tables2order <- c("Saliva","Midturbinate Swab", "Fomite","G-II Coarse Aerosol","G-II Fine Aerosol")

Table2_1 <- tables2order %>% matrix(ncol=1) %>% as.data.frame(stringsAsFactors=F)
colnames(Table2_1) <- "Sample Type"
Table2_1 <- Table2_1 %>% left_join(Table2,by="Sample Type")

#write.csv(Table2_1,file="../output/repo_table_2_semiformatted.csv",row.names=F)
```

#total EBA row
```{r}
df_eba <- dF %>% 
  filter(sample_type %in% c("G-II Fine Aerosol", "G-II Coarse Aerosol")) %>% 
  select(subject_id, sample_date, sample_type, cens, sample_quant, any_rep_lod1, all_rep_loq, culture_status, sample_id, nd_lod_loq)


#summarize number of positive samples and participants
n_subj_total <- length(unique(df_eba$subject_id))
n_pos_subj_lod_total <- df_eba %>% distinct(subject_id, sample_date, sample_type, .keep_all = T) %>% 
  filter(any_rep_lod1 == TRUE) %>% 
  select(subject_id)%>%
  unique() %>% 
  nrow()
n_pos_subj_loq_total <- df_eba %>% distinct(subject_id, sample_date, sample_type, .keep_all = T) %>% 
  filter(all_rep_loq == TRUE) %>% 
  select(subject_id)%>%
  unique() %>% 
  nrow()
n_pos_subj_culture_total <- df_eba %>% filter(culture_status!="not cultured") %>%
  distinct(sample_id, sample_type,.keep_all = T) %>%
  select(subject_id) %>% 
  unique() %>% 
  nrow()
n_pos_subj_culture_pos <- df_eba %>% filter(culture_status =="TRUE") %>%
  distinct(sample_id, sample_type,.keep_all = T) %>%
  select(subject_id) %>% 
  unique() %>% 
  nrow()
  

n_samp_total <- df_eba %>% distinct(subject_id, sample_date, sample_type) %>%
  summarize(n())
n_pos_samp_lod_total <- df_eba %>% distinct(subject_id, sample_date, sample_type, .keep_all = T) %>% summarize(sum(any_rep_lod1))
n_pos_samp_loq_total <-df_eba %>% distinct(subject_id, sample_date, sample_type, .keep_all = T) %>% summarize(sum(all_rep_loq))

n_culture_total <- df_eba %>% filter(culture_status!="not cultured") %>%
                distinct(sample_id, sample_type,.keep_all = T) %>%
                summarize(n())
n_pos_culture_total <- df_eba %>% filter(culture_status =="TRUE") %>%
                distinct(sample_id, sample_type,.keep_all = T) %>%
                summarize(n())
                          
#calculate percentage
#subject percentage
n_pos_subj_lod_total_perc=round((n_pos_subj_lod_total/n_subj_total)*100,0)
n_pos_subj_loq_total_perc=round((n_pos_subj_loq_total/n_subj_total)*100,0)
n_pos_subj_culture_total_perc=round((n_pos_subj_culture_pos/n_pos_subj_culture_total)*100,0)

#sample percentage
n_pos_samp_lod_total_perc=round((n_pos_samp_lod_total/n_samp_total)*100,0)
n_pos_samp_loq_total_perc=round((n_pos_samp_loq_total/n_samp_total)*100,0)
n_pos_culture_total_perc=round((n_pos_culture_total/n_culture_total)*100,0)

#create wide format of df_eba for the calculation of GM and GSD
df_eba_wide <- df_eba %>% filter(sample_type == "G-II Fine Aerosol")  %>% 
  left_join((df_eba %>% filter(sample_type == "G-II Coarse Aerosol")), by = c("subject_id", "sample_date"))

df_eba_wide <- df_eba_wide %>% 
  mutate(cens_total = if_else(cens.x == 1 & cens.y == 1, 1, 0),
         sample_total = sample_quant.x + sample_quant.y, 
         sample_id = sample_id.x) %>% 
  mutate(mdfy_sample_total = if_else(sample_total == 0, 75, sample_total))%>% 
  mutate(ln_final_copies_total=log(mdfy_sample_total))

Z_total<- z_create_matrix(df_eba_wide)
cluster_total <- as.numeric(factor(df_eba_wide$subject_id))
cens_total <- df_eba_wide$cens_total
yL_total<- df_eba_wide$ln_final_copies_total
X <- matrix(rep(1, length(df_eba_wide$ln_final_copies_total)), ncol=1) #for intercept only

#### MODEL: Running the LMEC procedures: using REML ####

fit_reml <- lmec(yL = yL_total,
                  cens = cens_total,
                  X = X, 
                  Z = Z_total,
                  cluster=cluster_total,
                  method='ML',
                  maxstep=200)
  summary(fit_reml)
  print(fit_reml)
beta <- fit_reml$beta
sigma <- sqrt(fit_reml$varFix)
low_ci_fold_inc <- signif(exp(beta - 1.96*(sigma)), 2)
up_ci_fold_inc <- signif(exp(beta + 1.96*(sigma)), 2)
fold_inc <- signif(exp(beta), 2)  
gsd = signif(exp(fit_reml$sigma), digits = 2)

#calculate maximum value
df_eba_wide <- df_eba_wide %>% group_by(sample_id) %>% mutate(av_total_per_sample_id=mean(sample_total,na.rm = T))
max_total = signif(max(df_eba_wide$av_total_per_sample_id), digits = 2)

#final EBA row
eba_row <- c("Total EBA",
             #n_subj_total, 
             paste0(n_pos_subj_lod_total,"/",n_subj_total, " (",n_pos_subj_lod_total_perc,")"),
            # paste0(n_pos_subj_loq_total, "/",n_subj_total," (",n_pos_subj_loq_total_perc,")"),
             paste0(n_pos_subj_culture_pos,"/",n_pos_subj_culture_total, " (",n_pos_subj_culture_total_perc,")"),
            # n_samp_total,
             paste0(n_pos_samp_lod_total,"/",n_samp_total, " (",n_pos_samp_lod_total_perc,")"),
            # paste0(n_pos_samp_loq_total, " (",n_pos_samp_loq_total_perc,")"),
             paste0(n_pos_culture_total,"/",n_culture_total, " (",n_pos_culture_total_perc,")"),
             paste0(fold_inc, " (", low_ci_fold_inc,", ",up_ci_fold_inc,")"),
             max_total)
eba_row_df <- as.data.frame(matrix(eba_row, nrow=1))
colnames(eba_row_df) <- colnames(Table2_1)
Table2_1 <- rbind(Table2_1, eba_row_df)

tables2order_2 <- c("Saliva","Midturbinate Swab", "Fomite","G-II Coarse Aerosol","G-II Fine Aerosol", "Total EBA")

table_order2 <- tables2order_2 %>% matrix(ncol=1) %>% as.data.frame(stringsAsFactors=F)
colnames(table_order2) <- "Sample Type"
Table2_1 <- table_order2 %>% left_join(Table2_1,by="Sample Type")
```


```{r fix the scientific notation}
Table2_2 <- Table2_1
Table2_2$`Maximum RNA copies` <- Table2_2$`Maximum RNA copies` %>% sapply(function(x) {if (x!="-") {fixRNAscientific(x)} else {x}})
Table2_2$`GM (95% CI)` <- Table2_2$`GM (95% CI)` %>% sapply(function(x) {if (x!="-") {GMCIparse_fixsci(x)} else {x}})
Table2_2
```

```{r write final table}
write.csv(Table2_2, file="../output/si_tab3_viral_load.csv",row.names = F)
```

range of detectable EBA
```{r}
spr <- read.csv(file = "../working_files/nonpaired_pcr_sx_spr.csv")
spr_breath <- spr %>% filter(sample_type == "G-II Fine Aerosol") %>% 
  left_join(spr %>% filter(sample_type == "G-II Coarse Aerosol"), by = c("subject_id", "sample_date")) %>% 
  mutate(av_quant_total = av_quant.x + av_quant.y)

#fine
fine_range<- signif(range((spr_breath %>% filter(!(av_quant.x ==0)))$av_quant.x), digits =2)
#coarse
coarse_range <- signif(range((spr_breath %>% filter(!(av_quant.y ==0)))$av_quant.y), digits =2)
#fine+coarse
total_range <- signif(range((spr_breath %>% filter(!(av_quant_total ==0)))$av_quant_total), digits =2)
range_detectable_EBA <- paste("fine:", fine_range,"coarse:", coarse_range,"total:", total_range)
write.csv(range_detectable_EBA,file="../output/range_detectable_EBA_in_si_tab3_script.txt",row.names=F)
```

range of EBA for children
```{r}
spr_breath_child <- spr_breath %>% filter(age_entry.x < 18)
unique(spr_breath_child$subject_id)
#fine
fine_range<- signif(range((spr_breath_child %>% filter(!(av_quant.x ==0)))$av_quant.x), digits =2)
#coarse
coarse_range <- signif(range((spr_breath_child %>% filter(!(av_quant.y ==0)))$av_quant.y), digits =2)
#fine+coarse
total_range <- signif(range((spr_breath_child %>% filter(!(av_quant_total ==0)))$av_quant_total), digits =2)
range_detectable_EBA_child <- paste("fine:", fine_range,"coarse:", coarse_range,"total:", total_range)
write.csv(range_detectable_EBA_child,file="../output/range_detectable_EBA_child_in_si_tab3_script.txt",row.names=F)
```

