---
title: "violin"
author: "Jianyu"
date: "3/6/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggpubr)
library(scales)
library(grid)
library(ggthemes)
set.seed(42)
```

```{r include=FALSE}
# Theme for display parameters
theme_Publication <- function(base_size=14, base_family="sans") {
      (theme_foundation(base_size=base_size, base_family=base_family)
       + theme(plot.title = element_text(face = "bold",
                                         size = rel(1.2), hjust = 0.5),
               text = element_text(),
               panel.background = element_rect(colour = NA),
               plot.background = element_rect(colour = NA),
               panel.border = element_rect(colour = NA),
               axis.title = element_text(face = "bold",size = rel(1)),
               axis.title.y = element_text(angle=90,vjust =2),
               axis.title.x = element_text(vjust = -0.2),
               axis.text = element_text(), 
               axis.line = element_line(colour="black"),
               axis.ticks = element_line(),
               panel.grid.major = element_line(colour="#f0f0f0"),
               panel.grid.minor = element_blank(),
               legend.key = element_rect(colour = NA),
               legend.position = "bottom",
               legend.direction = "horizontal",
               legend.key.size= unit(0.2, "cm"),
               legend.margin = unit(0.2, "cm"),
               legend.title = element_text("S.gene dropout",face="italic"),
               plot.margin=unit(c(10,5,5,5),"mm"),
               strip.background=element_rect(colour="#f0f0f0",fill="#f0f0f0"),
               strip.text = element_text(face="bold")))}

scale_fill_Publication <- function(...){
      discrete_scale("fill","Publication",manual_pal(values = c("#b03838","#386cb0","#7fc97f","#ef3b2c","#662506","#a6cee3","#fb9a99","#984ea3","#ffff33")), ...)}

scale_colour_Publication <- function(...){
      discrete_scale("colour","Publication",manual_pal(values = c("#b03838","#386cb0","#7fc97f","#ef3b2c","#662506","#a6cee3","#fb9a99","#984ea3","#ffff33")), ...)}
# to use this: scale_fill_Publication()+scale_colour_Publication()+theme_Publication()
```
# use replicate per row data from nonpaired sets
```{r}
rpr_nonpaired <- read.csv("../working_files/nonpaired_pcr_sx_rpr.csv")
```

# Fig 1 
```{r}
#explore culture status
pcr_dat_violin2 <- rpr_nonpaired %>% 
    mutate(culture_status=factor(culture_status,
                            levels = c("FALSE","TRUE","not cultured"),
                            labels = c("negative","positive","not cultured")))

pcr_dat_violin2$ngene_CT <- pcr_dat_violin2$ct_ngene_qpcr
pcr_dat_violin2$ngene_CT[which(pcr_dat_violin2$ngene_CT==-1)] <- NA #replace CT of non detects with NA so it won't contribute to the mean estimate

pcr_dat_violin2 <- pcr_dat_violin2 %>% group_by(sample_id) %>% mutate(av_ngene_CT=mean(ngene_CT,na.rm = T)) #average CT values so non-detects are excluded from the mean

pcr_dat_violin2$id_date <- paste(pcr_dat_violin2$subject_id,pcr_dat_violin2$sample_date,sep="-") # helper
pcr_dat_violin2$av_ngene <- (pcr_dat_violin2$av_quant + 1) %>% log10() # add 1 to the copy numbers to avoid undefined log 0
pcr_dat_violin2 <- pcr_dat_violin2 %>% distinct(sample_id,.keep_all = T) %>% #keep one replicate per sample
  mutate(av_ngene_CT=if_else(is.nan(av_ngene_CT),41,av_ngene_CT)) %>%
  ungroup() #replace Ct value of non-detects with 41

pcr_dat_violin2$sample_type <- as.character(pcr_dat_violin2$sample_type)
pcr_dat_violin2$sample_type[which(pcr_dat_violin2$sample_type=="G-II Coarse Aerosol")] <- "Coarse aerosol without mask"
pcr_dat_violin2$sample_type[which(pcr_dat_violin2$sample_type=="G-II Coarse Aerosol mask")] <- "Coarse aerosol with mask"
pcr_dat_violin2$sample_type[which(pcr_dat_violin2$sample_type=="G-II Fine Aerosol")] <- "Fine aerosol without mask"
pcr_dat_violin2$sample_type[which(pcr_dat_violin2$sample_type=="G-II Fine Aerosol mask")] <- "Fine aerosol with mask"

pcr_dat_violin2 <- pcr_dat_violin2 %>% filter(sample_type %in% c("Midturbinate Swab","Phone Swab","Saliva","Coarse aerosol without mask","Coarse aerosol with mask","Fine aerosol without mask","Fine aerosol with mask"))
#
pcr_dat_violin2 <- pcr_dat_violin2 %>% 
  mutate(sample_type=factor(sample_type,
                            levels = c("Midturbinate Swab","Saliva","Phone Swab","Coarse aerosol without mask","Coarse aerosol with mask","Fine aerosol without mask","Fine aerosol with mask"),
                            labels = c("MTS","Saliva","Fomite","Coarse aerosol","Coarse aerosol +mask","Fine aerosol","Fine aerosol +mask")))
pcr_dat_violin2 <-pcr_dat_violin2 %>% group_by(sample_type) %>% mutate(n=sum(!is.na(av_ngene))) #count number of log RNA copies per sample type to be displayed in the plots

table(pcr_dat_violin2$culture_status)

breath_violin_dF_cult <- pcr_dat_violin2 %>% mutate(sampletype_culturestatus=factor(paste("Culture",culture_status,sample_type)))

table(breath_violin_dF_cult$sampletype_culturestatus)

breath_violin_dF_cult <- breath_violin_dF_cult %>% group_by(sampletype_culturestatus) %>% mutate(n_culture=n())
breath_violin_dF_cult1 <- breath_violin_dF_cult %>% filter(!(culture_status %in% c("not cultured","imputed sample")) & !grepl("Spray",sample_type)) %>% rename(`Culture status`=culture_status)

# color the fine aerosol masked culture positive points red (#bo3838)
breath_violin_dF_cult1$pointcolor <- "black"
breath_violin_dF_cult1$pointcolor[breath_violin_dF_cult1$sampletype_culturestatus=="Culture positive Fine aerosol +mask"] <- "#b03838"
breath_violin_dF_cult1$pointcolor[breath_violin_dF_cult1$sampletype_culturestatus=="Culture positive Coarse aerosol"] <- "#b03838"


breath_violin_dF_cult1$facet_cat[breath_violin_dF_cult1$sampletype_culturestatus %in% c("Culture negative MTS", "Culture positive MTS","Culture negative Saliva","Culture positive Saliva","Culture negative Fomite", "Culture positive Fomite")] <- "Swabs and saliva"

breath_violin_dF_cult1$facet_cat[breath_violin_dF_cult1$sampletype_culturestatus %in% c("Culture negative Coarse aerosol","Culture positive Coarse aerosol","Culture negative Fine aerosol","Culture positive Fine aerosol")] <- "Without mask"

breath_violin_dF_cult1$facet_cat[breath_violin_dF_cult1$sampletype_culturestatus %in% c("Culture negative Coarse aerosol +mask", "Culture positive Coarse aerosol +mask","Culture negative Fine aerosol +mask","Culture positive Fine aerosol +mask")] <- "With mask"


violin_culture1 <- breath_violin_dF_cult1 %>%
  filter(facet_cat=="Swabs and saliva") %>% 
  ggplot(aes(x = sampletype_culturestatus, y=av_ngene, fill=`Culture status`,color=mask_yn)) + 
  geom_violin(lwd=0,color="black",width=1.1,position=position_dodge(width=3),alpha = 0.9) +
  geom_point(lwd=1, color=(breath_violin_dF_cult1 %>% filter(facet_cat=="Swabs and saliva"))$pointcolor,position=position_jitter(h=0.05,w=.1,seed=42)) +
  geom_text(aes(y=-0.5,label=paste("n=",n_culture)),position = position_dodge(0.5),color="black") +
  labs(y = "log10 RNA copies", x = "") +
  theme(axis.text.x = element_text(angle = 0),legend.position = "bottom") +
  scale_y_continuous(limits=c(-0.8,10), breaks = c(0:10)) +
  scale_x_discrete(labels = wrap_format(10.5)) +
  scale_fill_manual(labels=c("negative","positive"),values =c("#386CB0","#B03838")) + # switch the colors to match the levels
  theme_bw()

violin_culture2 <- breath_violin_dF_cult1 %>%
  filter(facet_cat=="Without mask") %>% 
  ggplot(aes(x = (sampletype_culturestatus), av_ngene,fill=`Culture status`,color=mask_yn)) + 
  geom_violin(lwd=0,color="black",width=1.1,position=position_dodge(width=3),alpha =0.9) +
  geom_point(lwd=1,color=(breath_violin_dF_cult1 %>% filter(facet_cat=="Without mask"))$pointcolor,position=position_jitter(h=0.05,w=.1,seed=42)) +
  geom_text(aes(y=-0.5,label=paste("n=",n_culture)),position = position_dodge(0.5),color="black") +
  labs(y = "log10 RNA copies", x = "") +
  theme(axis.text.x = element_text(angle = 0),legend.position = "bottom") +
  scale_y_continuous(limits=c(-0.8,10), breaks = c(0:10)) +
  scale_x_discrete(labels = wrap_format(10.5)) +
  scale_fill_manual(labels=c("negative","positive"),values =c("#386CB0","#B03838")) + # switch the colors to match the levels
  theme_bw()

violin_culture <- ggarrange(violin_culture1, violin_culture2,
                            labels = c("a","b"),
                            font.label = list(size = 20, face = "bold"),
                      ncol = 2, nrow=1,
                      common.legend = T,
                      legend = "bottom",
                      align = "h")

violin_culture
ggsave(violin_culture,filename="../output/fig1_violin_viral_load.png",device="png",width=11,height=5.75,units="in")
ggsave(violin_culture,filename="../output/tiff/fig1_violin_viral_load.tiff",device="tiff",width=11,height=5.75,units="in", dpi=600,compression="lzw")
```

